language: bash

os: windows

services: docker

before_install:
  - docker version
  
install:
  - docker build -t coatisoftware/test:1 .

script:
  - docker run coatisoftware/test:1 /entrypoint.sh World
